---
spring:
  config:
    location: /application.yml,classpath:/application.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/quiver
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog.xml
server:
  port: 8081
  servlet:
    contextPath: /api
